const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf8');

const s1 = code.indexOf('const CHALLENGES = [');
const s2 = code.indexOf('const MOCK_USERS = [');

const newCHALLENGES = `const CHALLENGES = [
  // Level 1: Basics
  { id: 'sqli', level: 1, name: 'Classic SQL Injection', desc: 'Log in as the administrator using a malformed query.', diff: 'Easy', explanation: "You manipulated the database query into always returning true by entering a payload like ' OR 1=1. In a real backend, this tricks the database into ignoring the password check, effectively logging you in as the first user in the database (usually the admin). Mitigation: ALWAYS use parameterized queries or prepared statements, which treat your input strictly as data, not executable code." },
  { id: 'xss', level: 1, name: 'Reflected XSS', desc: 'Inject HTML into the search bar.', diff: 'Medium', explanation: "The application took your search input and reflected it directly back onto the HTML page without sanitizing it. This allows an attacker to inject malicious JavaScript (like stealing cookies or redirecting users) simply by tricking a victim into clicking a crafted link. Mitigation: Context-aware output encoding (escaping characters like <, >, &, \\", and ') before rendering user input in the browser." },
  { id: 'logic', level: 1, name: 'Business Logic Flaw', desc: 'Manipulate your cart for a negative balance.', diff: 'Medium', explanation: "You exploited a flaw in how the application handles cart quantities. By entering a negative number, the system calculated a negative total price (effectively owing you money). This is a logic flaw, not a technical injection. Mitigation: Implement strict, server-side boundary validation to ensure quantities are positive integers and total prices are correctly computed." },
  { id: 'idor', level: 1, name: 'Forced Browsing', desc: 'Access the hidden admin panel.', diff: 'Easy', explanation: "You navigated directly to an administrative endpoint that was not linked in the main UI, but you weren't actually logged in as an admin. The application relied on 'Security through Obscurity' (hiding the link) instead of actually checking your permissions. Mitigation: Implement robust, server-side access control checks on every privileged route or action." },
  { id: 'promo', level: 1, name: 'Information Disclosure', desc: 'Find the hidden developer promo code.', diff: 'Easy', explanation: "You found a hardcoded 'secret' promo code left behind in the client-side JavaScript. Everything sent to the client's browser (HTML, CSS, JS) is publicly readable. Mitigation: Never store secrets, API keys, or administrative codes in frontend code. Always validate logic like promo codes on the secure backend." },

  // Level 2: Identification & Authentication
  { id: 'xss_stored', level: 2, name: 'Stored XSS', desc: 'Leave a malicious review containing HTML.', diff: 'Medium', explanation: "Unlike Reflected XSS, you managed to save your malicious HTML payload permanently into the application's database (via the feedback form). Now, every time any user visits the community feedback section, your malicious script will execute in their browser. Mitigation: Implement strict input validation on the server side and safely encode all output when rendering it." },
  { id: 'review_tamper', level: 2, name: 'Identity Spoofing', desc: 'Submit a review as another user.', diff: 'Hard', explanation: "You modified the 'Author Name' field when submitting a review, allowing you to post feedback masquerading as someone else (like the Admin). The server blindly trusted the client-provided author string. Mitigation: Read the author's identity directly from their secure, server-side session token, never from an untrusted client payload." },
  { id: 'bac_admin', level: 2, name: 'Broken Access Control', desc: 'Clear system logs as a normal user.', diff: 'Medium', explanation: "You executed an administrative action (clearing the debug logs) while logged in as a standard user. Even though the button might be hidden for normal users, the underlying function or API did not actually verify your role before executing the action. Mitigation: Always verify the user's role and permissions on the server side before performing sensitive operations." },
  { id: 'jwt_weak', level: 2, name: 'Mass Assignment', desc: 'Elevate your privileges to Admin via proxy.', diff: 'Medium', explanation: "By intercepting and modifying the JSON payload sent during a profile update, you injected a 'role: admin' field. Because the server merged the entire incoming JSON object directly into your user record without checking the keys, you successfully elevated your privileges. Mitigation: Use strict allowlists for updates; explicitly define exactly which fields a user is permitted to modify." },
  { id: 'debug_logs', level: 2, name: 'Data Exposure', desc: 'Find hidden logs by tapping the version.', diff: 'Easy', explanation: "You uncovered a hidden developer 'backdoor' by repeatedly tapping the app version. This exposed internal system logs that often contain sensitive information like stack traces, credentials, or architectural details. Mitigation: Completely remove developer features, debug endpoints, and verbose logging before deploying applications to production." },

  // Level 3: Routing & Client Logic
  { id: 'dom_xss', level: 3, name: 'DOM-based XSS', desc: 'Trigger an alert via the URL view router.', diff: 'Hard', explanation: "You injected malicious code through the URL hash which was then directly executed by the application's client-side JavaScript (via a vulnerable 'dangerouslySetInnerHTML' or similar sink). The payload never even went to the server. Mitigation: Avoid using unsafe methods to manipulate the DOM, and validate/sanitize all fragments read from the URL." },
  { id: 'open_redirect', level: 3, name: 'Open Redirect', desc: 'Redirect the app to a malicious domain.', diff: 'Medium', explanation: "You manipulated a redirect parameter to send the user to an external, potentially malicious domain (evil.com). Attackers use this to craft phishing links that appear to come from the legitimate domain, tricking users into entering credentials. Mitigation: Implement an allowlist of permitted redirect domains, or rely on internal map keys instead of raw URLs." },
  
  // Level 4: Configuration & Secrets
  { id: 'ssrf', level: 4, name: 'Server-Side Request Forgery', desc: 'Fetch internal resources via the admin fetcher.', diff: 'Hard', explanation: "You manipulated a server-side fetch feature to make requests to internal, restricted IP addresses (like localhost or internal networks). This allows attackers to bypass firewalls and access internal admin panels or sensitive metadata APIs. Mitigation: Implement strict network-level firewalls, disable the following of redirects, and aggressively validate the format and target of requested URLs." },
  { id: 'crypto', level: 4, name: 'Weak Cryptography', desc: 'Decode the secret dev code.', diff: 'Medium', explanation: "You discovered a 'secret' developer code that was merely encoded using Base64, not cryptographically encrypted. Encoding is just a format change and provides zero security or confidentiality. Mitigation: If secrets must be stored securely, use strong, modern encryption algorithms (like AES) with securely managed keys, never just encoding or hashing." },

  // Level 5: Server-Side Execution
  { id: 'ssti', level: 5, name: 'SSTI', desc: 'Execute server-side templates in reviews.', diff: 'Hard', explanation: "By inputting specifically formatted brackets (like {{7*7}}), you tricked the application's templating engine into mathematically evaluating the payload. In a real exploit, this Server-Side Template Injection can be escalated to execute arbitrary system code on the underlying server. Mitigation: Never evaluate or execute user input as raw template code; use safe, logic-less templates." },
  { id: 'path_traversal', level: 5, name: 'Path Traversal', desc: 'Read /etc/passwd via the fetcher.', diff: 'Medium', explanation: "You bypassed path restrictions by using 'file://' protocols to read arbitrary local files from the server's filesystem, specifically '/etc/passwd'. This exposes sensitive configuration files and user data. Mitigation: Disallow file:// protocol handlers, sanitize inputs to remove directory traversal characters (../), and enforce strict chroot environments." },

  // Level 6: Advanced Evasion
  { id: 'waf_bypass', level: 6, name: 'WAF Bypass', desc: 'Bypass the \\"no-script\\" filter using special encoding.', diff: 'Hard', explanation: "You successfully bypassed the Web Application Firewall (WAF) rule that was specifically trying to block '<script>' tags. You did this by using an alternative payload (like an <img> tag with an onerror event) that achieved the same result without triggering the naive string match. Mitigation: Do not rely solely on blocklists. Implement robust, context-aware output encoding across the entire application." },
  { id: 'null_byte', level: 6, name: 'Null Byte Injection', desc: 'Upload a forbidden file type using %00.', diff: 'Hard', explanation: "You used a Null Byte character (%00) to fool the application's file extension check. While the app thought it was validating an innocent file type, the underlying system terminated the string early, resulting in executing a malicious payload. Mitigation: Use modern high-level languages and frameworks that handle null bytes safely, and validate files by their actual headers/MIME types, not just extensions." },

  // Level 7: API Abuse
  { id: 'idor_api', level: 7, name: 'IDOR / API Leak', desc: 'Download another user\\'s backup data.', diff: 'Hard', explanation: "You changed the email address parameter in an API request and successfully downloaded the backup data for a completely different user without knowing their password. This Insecure Direct Object Reference (IDOR) occurred because the server didn't verify that your session actually had rights to the requested email account. Mitigation: Implement strict, server-side object-level access controls." },
  { id: 'rate_limit', level: 7, name: 'No Rate Limiting', desc: 'Simulate a brute force on the login secret.', diff: 'Medium', explanation: "You repeatedly hammered a sensitive endpoint simulating a brute-force attack on a secret code. Because the application lacked rate limits or lockout mechanisms, you could try thousands of variations until you found the correct answer. Mitigation: Implement IP/User-based rate limiting, account lockouts after failed attempts, and CAPTCHAs where appropriate." },

  // Level 8: Prototype Pollution
  { id: 'proto_pollute', level: 8, name: 'Prototype Pollution', desc: 'Overwrite global object properties.', diff: 'Expert', explanation: "You abused a poorly configured object merge function to inject a 'role' property directly into JavaScript's global Object prototype via the __proto__ property. This affected every object in the application, suddenly elevating your status to an admin everywhere simultaneously. Mitigation: When dynamically parsing or merging objects, explicitly filter out prototype-modifying keys, or instantiate objects using Object.create(null) so they lack a prototype." }
];
`;

code = code.substring(0, s1) + newCHALLENGES + '\n' + code.substring(s2);

fs.writeFileSync('src/App.tsx', code);
